### ISSUE TITLE
Process slack links

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-appservice-webhooks#14]
Blocked by #13 

Only do transforms on slack endpoint.

* `<https://alert-system.com/alerts/1234|Click here>` becomes `<a href='https://alert-system.com/alerts/1234'>Click here</a>`
* `<@user:matrix.org:Bob>` becomes `<a href='https://matrix.to/#/user/@user:matrix.org'>Bob</a>`
* `<#room:matrix.org|Room>` becomes `<a href="https://matrix.to/#/#room:matrix.org">Room</a>`

**Comment by turt2live** [comment]
https://api.slack.com/docs/message-formatting#how_to_display_formatted_messages

**Comment by z3ntu** [comment]
Bump? Also, if it isn't too hard to implement without having ever looked at the source of this bridge (or other bridges) I can try to do it if you would give me a few hints where to start.

**Comment by turt2live** [comment]
The core of the format processing is here: https://github.com/turt2live/matrix-appservice-webhooks/tree/master/src/processing

Things are defined into very tiny layers that do the microprocessing on the text. `WebhookReceiver` defines an ordered sequence for which layers to apply.
