### ISSUE TITLE
Configurable localpart

### ISSUE THREAD

**Issue by joenas** [turt2live/matrix-appservice-webhooks#22]
Would it be possible to use an existing user (i.e. a "bot" user) as the bridge?
My use case is that I have a user (say @superbot:example.com) with several backends connected, like go-neb and hubby, and I'd like to have webhooks as well without adding another user to the room.

**Comment by turt2live** [comment]
The bridge works by adding virtual users based on the display name. For more single-user type webhooks, the slackapi in go-neb would probably work better.

**Comment by joenas** [comment]
Yeah I know, but I meant the bridge user. So one of my existing "bots" could invite the virtual users.

**Comment by turt2live** [comment]
It's not currently possible, but should be. I'll use this ticket to track that

**Comment by joenas** [comment]
👌🏻💯

**Comment by joenas** [comment]
I modified the registration file to change localpart and the bridge starts up fine and starts "requesting to join room", then I get an error like this:
```
[matrix-appservice-bridge] [-] POST http://matrix_synapse_1:8008/_matrix/client/r0/register (AS) HTTP 400 Error: {"errcode":"M_USER_IN_USE","error":"User ID already taken."}
```

I'm assuming its the already existing user/bot in the room. _But_, I've got this working with another bridge of mine so maybe it's something in the code that assumes that the bridge is always a new user?

**Comment by turt2live** [comment]
The code assumes the user, but that error is normal for the startup routine. This is open as a reminder to myself to make it support an alternate user.

**Comment by joenas** [comment]
I figured I'd spare you the trouble!
