### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by joenas** [turt2live/matrix-appservice-webhooks#23]
Im trying to dockerize this project but I'm a bit at loss at how to deal with registration file generation. Right now my best bet is to do it in the image and have the user mount a dir to access it. Feels wrong but generating it outside of the container means depending on node which kinda defeats the purpose..

You got any ideas?

**Comment by turt2live** [comment]
The registration file can always be generated by hand. The underlying bridge library is just helpful in generating it.

The only thing that cannot be hardcoded is the asToken and the hsToken (these must be generated/random).

**Comment by joenas** [comment]
Ah, right. Still it would be nice if it could just work (more or less) for the user. I guess volumes is the way to go.
