### ISSUE TITLE
Optional parameter for m.notice

### ISSUE THREAD

**Issue by joenas** [turt2live/matrix-appservice-webhooks#27]
It would be nice to be able to send notices as well

**Comment by joenas** [comment]
Another layer and something like `if webhook.type && webhook.type == 'notice'`? I could put it together tomorrow.

**Comment by turt2live** [comment]
`type` is eventually going to be a reserved keyword for incoming/outgoing. I'd probably call it something like `msgtype` just to be consistent with matrix. Just for fun, it could also support emotes.

**Comment by joenas** [comment]
Sure thing. Emotes _are_ fun! :P
