### ISSUE TITLE
Bridge stays stuck at M_USER_IN_USE

### ISSUE THREAD

**Issue by starcraft66** [turt2live/matrix-appservice-webhooks#37]
The _webhook user was already created when I started the bridge so it just got stuck at the M_USER_IN_USE error. I tried deactivating the _webhook account using the Admin API but I still get the same error:

Loading config file /app/config/config.yaml
May-19-2018 07:09:59.743 +00:00 info [index] Preparing database...
May-19-2018 07:09:59.744 +00:00 info [WebhookStore] Running migrations
[INFO] No migrations to run
[INFO] Done
Sat, 19 May 2018 07:09:59 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at ../node_modules/sequelize/lib/sequelize.js:242:13
May-19-2018 07:09:59.876 +00:00 info [index] Preparing bridge...
May-19-2018 07:09:59.876 +00:00 info [WebhookBridge] Constructing bridge
May-19-2018 07:09:59.877 +00:00 info [WebhookBridge] Starting bridge
May-19-2018 07:10:00.208 +00:00 info [WebhookBridge] Updating appearance of bridge bot
May-19-2018 07:10:00.226 +00:00 warn [index] No provisioning API token is set - the provisioning API will not work for this bridge
May-19-2018 07:10:00.228 +00:00 info [WebService] API now listening on 0.0.0.0:4501
May-19-2018 07:10:00.336 +00:00 error [matrix-appservice-bridge] [-] POST https://nerdsin.space/_matrix/client/r0/register (AS) HTTP 400 Error: {"errcode":"M_USER_IN_USE","error":"User ID already taken."}

**Comment by turt2live** [comment]
That kind of error indicates that the application service was not correctly installed in Synapse. Instead, there should be an error that says something like "The application service has already registered this user". 

Deactivating the account will cause problems with the bridge, so I recommend undoing that change.

**Comment by starcraft66** [comment]
I'm not sure how to "undo" a deactivation. I tried issuing a password reset for the account and it threw some M_UNKNOWN error.

I ended up restarting Synapse and the bridge and the log seems to get a little bit further, possibly indicating that the bot account does work because it is able to update the display name and stuff.

I made sure that the appservice-registration-webhooks.yaml files are identical in the synapse data directory and in the webhooks app directory.

However, when I invite the bot to a room it does not auto-join it. I made sure that the service is registered on the synapse side and I see the following in the synapse log:

2018-05-19 13:18:18,427 - synapse.config.appservice - 80 - INFO - None - Loaded application service: ApplicationService: {'sender': '@_webhook:nerdsin.space', 'server_name': 'nerdsin.space', 'url': 'http://matrix_appservice_webhooks_1:9000', 'rate_limited': False, 'id': '60e342d66fda58f8b4e399741ba26a519448b382c430e36f4423976e8054b930', 'token': '<redacted>', 'namespaces': {'aliases': [], 'rooms': [], 'users': [{'regex': <_sre.SRE_Pattern object at 0x7f95406b3a50>, 'exclusive': True}]}, 'hs_token': '<redacted>', 'protocols': set([])}

This is the log from the webhooks bridge:

May-19-2018 13:18:40.170 +00:00 info [index] Preparing database...
May-19-2018 13:18:40.172 +00:00 info [WebhookStore] Running migrations
May-19-2018 13:18:40.290 +00:00 info [index] Preparing bridge...
May-19-2018 13:18:40.290 +00:00 info [WebhookBridge] Constructing bridge
May-19-2018 13:18:40.291 +00:00 info [WebhookBridge] Starting bridge
May-19-2018 13:18:40.934 +00:00 verbose [ProvisioningService] Received intent. Using account @_webhook:nerdsin.space
May-19-2018 13:18:40.935 +00:00 verbose [InteractiveProvisioner] Received bridge. Using default bot intent
May-19-2018 13:18:40.936 +00:00 verbose [WebhookReceiver] Received bridge.
May-19-2018 13:18:40.937 +00:00 info [WebhookBridge] Updating appearance of bridge bot
May-19-2018 13:18:40.948 +00:00 verbose [matrix-appservice-bridge] [-] GET https://nerdsin.space/_matrix/client/r0/joined_rooms (AS) Body: 
May-19-2018 13:18:40.960 +00:00 warn [index] No provisioning API token is set - the provisioning API will not work for this bridge
May-19-2018 13:18:40.962 +00:00 info [WebService] API now listening on 0.0.0.0:4501
May-19-2018 13:18:41.010 +00:00 verbose [WebhookStore [SQL]] Executing (default): SELECT `id`, `objectId`, `key`, `value` FROM `account_data` AS `account_data` WHERE `account_data`.`objectId` = 'bridge';
May-19-2018 13:18:41.025 +00:00 verbose [matrix-appservice-bridge] [-] POST https://nerdsin.space/_matrix/client/r0/register (AS) Body: {"auth":{},"username":"_webhook"}
May-19-2018 13:18:41.059 +00:00 verbose [matrix-appservice-bridge] [-] GET https://nerdsin.space/_matrix/client/r0/joined_rooms (AS) HTTP 200 {"joined_rooms":[]}
May-19-2018 13:18:41.283 +00:00 error [matrix-appservice-bridge] [-] POST https://nerdsin.space/_matrix/client/r0/register (AS) HTTP 400 Error: {"errcode":"M_USER_IN_USE","error":"User ID already taken."}
May-19-2018 13:18:41.285 +00:00 verbose [matrix-appservice-bridge] [-] GET https://nerdsin.space/_matrix/client/r0/profile/%40_webhook%3Anerdsin.space/displayname (@_webhook:nerdsin.space) Body: 
May-19-2018 13:18:41.295 +00:00 verbose [matrix-appservice-bridge] [-] GET https://nerdsin.space/_matrix/client/r0/profile/%40_webhook%3Anerdsin.space/displayname (@_webhook:nerdsin.space) HTTP 200 {"displayname":"Webhook Bridge"}

**Comment by turt2live** [comment]
Just to cover a couple things:
* Is `http://matrix_appservice_webhooks_1:9000` accessible?
* Does the webhook bridge log say anything about getting an invite?
* Are there any errors in the synapse log? (Should be able to grep for `matrix_appservice_webhooks_1` to see what it is doing).

**Comment by starcraft66** [comment]
Thanks a lot, I guess that clears it up. I was able ot get everything connected and running using the container's ip address. I'll have to set a static IP to the container to ensure it never changes then.
