### ISSUE TITLE
Broken HTML generated by from_slack_attachments.js (missing closing quote on attribute)

### ISSUE THREAD

**Issue by sa-lr** [turt2live/matrix-appservice-webhooks#41]
E.g.  `combinedHtml += "<blockquote data-mx-border-color='" + color + "'>";`

Should be `combinedHtml += "<blockquote data-mx-border-color=\"" + color + "\">";`

This causes postprocess/upload_images.js to write content to matrix.event.formatted_body with nothing contained in any of the HTML tags, resulting in blank messages.

Replacing all `'` with `\"` in from_slack_attachments.js fixes.

**Comment by turt2live** [comment]
What JSON is being posted to cause blank messages? The type of quotes there shouldn't matter at all.

**Comment by sa-lr** [comment]
Add me to the list of "thought single quotes weren't valid for XML attributes" :laughing:

There's a missing closing quote on line 37, looks like that was the actual problem.
