### ISSUE TITLE
database.json should magically work in Docker. (was: Webhook IDs are lost when service is restarted)

### ISSUE THREAD

**Issue by kapdap** [turt2live/matrix-appservice-webhooks#44]
Webhook IDs are disappearing every time I restart the service.

Log displays the warning **Using unknown data type INTEGER** during database migration.

```text
Loading config file /data/config.yaml
info [index] Preparing database...,
info [WebhookStore] Running migrations,
[INFO] Processed migration 20170708201820-create-bot-account-data-table,
[INFO] Processed migration 20170708235052-create-webhooks-table,
[WARN] Using unknown data type INTEGER,
[INFO] Processed migration 20170709024537-create-account-data-table,
[INFO] Processed migration 20170709024544-drop-bot-account-data,
[INFO] Done,
```

room-store.db and user-store.db files are created but empty (0kb).

20170709024537-create-account-data-table.js on line 19 I changed:

```
type: 'integer'
```
to
```
type: 'int'
```

(see https://github.com/db-migrate/shared/blob/8710b084b2b437a0bac3448eccd9d24ab08f08e1/data_type.js)

This removed the integer warning. *.db files are still empty and webhooks are lost after restart.

**Comment by turt2live** [comment]
Are you using Docker or running the bridge without it?

**Comment by kapdap** [comment]
Using Docker image

**Comment by turt2live** [comment]
Does your Docker command include a volume?

**Comment by kapdap** [comment]
Extract from my docker-compose.yml

```yml
  webhooks:
    image: turt2live/matrix-appservice-webhooks:latest
    hostname: webhooks
    volumes:
    - /mnt/volumes/matrix/webhooks/data:/data
```

I tried setting chmod 777 on the volume directory as a test but still creates empty sqlite files.

**Comment by turt2live** [comment]
Oh, you'll need to include a `database.json` file in the volume directory (`/mnt/volumes/matrix/webhooks/data/database.json` in your case). The file format is here: https://github.com/turt2live/matrix-appservice-webhooks/blob/master/config/database.json

The path should be `/data/development.db` and `/data/production.db`. I'm surprised I didn't make it do that in the Docker image though :/

**Comment by kapdap** [comment]
Ah, I had placed that database.json data folder. But the contents was:

```json
{
  "defaultEnv": {
    "ENV": "NODE_ENV"
  },
  "development": {
    "driver": "sqlite3",
    "filename": "db/development.db"
  },
  "production": {
    "driver": "sqlite3",
    "filename": "db/production.db"
  }
}
```

Replaced db/ with /data/ and /data/production.db was created. Webhooks remained after restart.

Appreciate your help. Thanks.

**Comment by turt2live** [comment]
Awesome! I'm going to leave this open for "make the database.json work correctly".
