### ISSUE TITLE
GitLab webhooks result in HTTP 400

### ISSUE THREAD

**Issue by starcraft66** [turt2live/matrix-appservice-webhooks#64]
When using the "Test" button on a self-hosted GitLab instance with a webhook url generated by the bridge, I get the following error message: "Hook executed successfully but returned HTTP 400 {"error":"Missing message text or attachments","success":false}".

The following message shows up in the bridge's log: "Oct-23-2019 15:29:11.155 +00:00 error [WebService [Hook 6vf25sU<redacted>B9ZEdapXKZBTstgpJ]] Invalid message: missing text or attachments"

**Comment by enannos** [comment]
I have the same issue...

**Comment by tripleawwy** [comment]
Use Project services (which is right below the webhook setting)

![image](https://user-images.githubusercontent.com/43851917/72254482-70e44a80-3604-11ea-81c2-dac52551dc12.png)

**Comment by xxxserxxx** [comment]
I get this as well trying a simple test message with curl:
```shell
$ curl -X POST -d '{ "text": "Build CI test message", "format": "plain", "displayName": "SourceHut CI", "avatarUrl": "http://i.imgur.com/IDOBtEJ.png" }' "https://webhooks.t2bot.io/api/v1/matrix/hook/abcdefg"
{"error":"Missing message text or attachments","success":false}
```
The README mentions needing to have permission to configure the room, but isn't clear about exactly what needs to be configured.   @tripleawwy , your comment in Jan last year was about configuring GitLab, not the Matrix room, right?

**Comment by turt2live** [comment]
You're better off using a more purpose-built bot/bridge for this: https://github.com/maubot/gitlab

The webhooks bridge is really just a polyfill for lack of proper support. Where proper support exists, please use that.

**Comment by xxxserxxx** [comment]
Fair enough.  It seems like overkill to have to maintain and run a service -- especially for people who may not have access to always-on VMs where they can run bots just to pass messages arong to Matrix.  However, I was pointed at [a wiki page](https://matrix.org/docs/guides/client-server-api#sending-messages) for posting messages directly to a matrix service, so writing a script to do this, triggered by the CI process, seems like the way to go.

**Comment by turt2live** [comment]
The idea is that this bridge also gets self-hosted, so that always-on VM requirement is still present. There are service providers out there which offer the gitlab bot though so you don't have to host it yourself. For example, I do: https://t2bot.io/gitlab/

Using the API directly is also a much more preferred route for things like CI.

**Comment by dimm0** [comment]
What supports prometheus alerts? I'm trying to set it up, and tried 3 different options already.. Now having dimension, goneb, webhook, and still getting "missing text or attachments"

**Comment by HarHarLinks** [comment]
you can try https://github.com/HarHarLinks/matrix-webhook-receiver for gitlab, github, ... full custom support. prometheus alerts should be possible.
