### ISSUE TITLE
GitLab commit activities are missing newlines

### ISSUE THREAD

**Issue by mkoppmann** [turt2live/matrix-appservice-webhooks#69]
We are using the Slack integration in GitLab to push notifications to a Matrix room. If someone pushes a bunch of new commits to a branch, the message is displayed in one long line (with the exception that the first commit sometimes has a newline).

This gets messy really quick. It would be great, if each commit would start on a new line, beginning with the commit hash.

![webhook](https://user-images.githubusercontent.com/21209717/78283505-68b5f000-750d-11ea-9c43-17cd58b732ad.png)

**Comment by turt2live** [comment]
Gitlab support is best done by other projects: https://github.com/maubot/gitlab
