### ISSUE TITLE
Direct message webhooks

### ISSUE THREAD

**Issue by mikeopensauce** [turt2live/matrix-appservice-webhooks#74]
Does anyone know if there is a way to use this system to generate webhooks that link to a user instead of a room?
I want to send messages to individual users from a monitoring system rather than posting them in a shared room.
Many thanks
Mike

**Comment by turt2live** [comment]
DMs are just rooms, so simply start a DM with the bot. You might have to trick it by dragging in a third user before asking for a webhook.

**Comment by mikeopensauce** [comment]
Simple when you know how! Many thanks
Mike
