### ISSUE TITLE
400 error on post

### ISSUE THREAD

**Issue by lgwapnitsky** [turt2live/matrix-appservice-webhooks#99]
Testing from two different applications that support webhooks, and receiving the following error in both:

`Unable to post to webhook: HTTP request failed: [400:BadRequest] [POST] at [https://webhooks.t2bot.io/api/v1/matrix/hook/blahblahblah`

**Comment by HarHarLinks** [comment]
Are you certain the applications you tried POSTed in the format required by the bridge as [demonstrated in the readme](https://github.com/turt2live/matrix-appservice-webhooks#json-body-for-posting-messages)?

Probably not. In that case, you need an adapter like https://github.com/HarHarLinks/matrix-webhook-receiver or any other service that is specialized to the actual body sent by the webhook.

**Comment by lgwapnitsky** [comment]
***@***.***:/opt/mx-puppet-discord# curl -H "Content-Type:
application\jason" --request POST --data '{
  "text": "Hello world!",
  "format": "plain",
  "displayName": "My Cool Webhook",
  "avatarUrl": "http://i.imgur.com/IDOBtEJ.png"
}'
http://matrix.wapnet.local.lan:9000/api/v1/matrix/hook/qIahB0Cv68TbpC5nB0TFHZVfedguJODbizbdLSUXq5DsG9MDJviNKyD5vRFU8EgI
{"error":"Missing message text or ***@***.***
:/opt/mx-puppet-discord#

*Larry G. Wapnitsky*


*E: ***@***.****
*Web: Larry.Wapnitsky.com <http://larry.wapnitsky.com/>Twitter:
@LGWapnitsky*

**Comment by lgwapnitsky** [comment]
and the "jason" was a typo. Even when fixed, I get the same error message

*Larry G. Wapnitsky*


*E: ***@***.****
*Web: Larry.Wapnitsky.com <http://larry.wapnitsky.com/>Twitter:
@LGWapnitsky*

**Comment by HarHarLinks** [comment]
> {"error":"Missing message text or ***@***.***
:/opt/mx-puppet-discord#

your error message is really unclear to me, it looks cut off?

> application\jason

it needs to be `application/json`, note the `/` direction

**Comment by lgwapnitsky** [comment]
Fixed that, same error. Will resend error message in a bit. Have to head out

**Comment by lgwapnitsky** [comment]
Now it's working
